version: "3.8"

services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - my_network

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1
    networks:
      - my_network


  spark-master:
    image: docker.io/bitnamilegacy/spark:3.4

    container_name: spark-master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DEBUG=1
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - my_network


  spark-worker:
    image: docker.io/bitnamilegacy/spark:3.4
    container_name: spark-worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - DEBUG=1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
