version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
  detailed:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s:%(lineno)d] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: detailed
    filename: logs/pipeline.log
    maxBytes: 5242880
    backupCount: 5
    level: DEBUG

root:
  level: INFO
  handlers: [console, file]
